### ISSUE TITLE
"items" property for "array"-type fields is array with single entry when it should be an object

### ISSUE THREAD

**Issue by liamhession** [wolverdude/GenSON#13]
Chalk it up to my poor understanding of JSON schema or this GenSON library itself if I'm way off-base here, but it seems to me that there is an incorrect schema being generated on the cases I'm using GenSON for.

I'll just put the test commands I ran. I took the generated schema over to http://www.jsonschemavalidator.net/ and tested it there. It failed exactly how I expected, based on my understanding of JSON Schema.

```
>>> import genson
>>> s = genson.Schema()
>>> s.add_object({"tags": ["stuff", "is"]})
>>> s.add_object({"tags": ["messed", "up", "stuff", "is"]})
>>> s.add_object({"tags": ["fully", "messed", "up"]})
>>> s.to_dict()
  {'required': ['tags'], 'type': 'object', 'properties': {'tags': {'items': [{'type': 'string'}], 'type': 'array'}}}
```

So then a couple objects I tested against it which I don't think should have passed but did were:
`{"tags": ["the", "last", "is", "a", 4]}`
`{"tags": ["or", true]}`
One that won't work because the schema that is generated will stop it is:
`{"tags": [true, "or"]}`

This is because the way it's specified means "The first element of the items array will be a string, I don't know about any after that"

This article was more informative to me than the official JSON Schema documentation:
http://spacetelescope.github.io/understanding-json-schema/reference/array.html

**Comment by wolverdude** [comment]
Yes. This is also the subject of Issue #8.

It has been fixed in [Genson 0.2.0](https://pypi.python.org/pypi/genson/0.2.0).
