### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by impredicative** [wolverdude/GenSON#17]
I would like to request support for Python 3.6 as documented in `setup.py` and at https://pypi.python.org/pypi/genson/ under Categories.

**Comment by wolverdude** [comment]
Thanks for opening the issue, @impredicative. All the tests pass in 3.6.2, so this should be a simple update. I'll get it out today.

**Comment by wolverdude** [comment]
Done. [Version 2.2](https://pypi.org/project/genson/0.2.2) is out. It's functionally identical to Version 0.2.1, but it mentions 3.6 support in the docs & Trove classifiers.
