### ISSUE TITLE
feature request: sort fields alphabetically

### ISSUE THREAD

**Issue by nqzero** [wolverdude/GenSON#18]
i'm processing json objects from multiple sources, each with multiple versions. i'm using the schema to both generate code and to detect when fields get added

however, some sources order the fields in different ways. as a result, the schemas that i generate have a different order, making it "hard" to compare them. it also results in larger diffs in the generated code

feature request: sort the fields in the schema alphabetically or provide a flag to enable this behavior

workaround: for detecting changes, i cat the 2 schemas and pipe them to "uniq -u". for generating code, i regenerate into a temp file and then manually apply the new fields (which i found using uniq above)

note: i'm using the command line interface. i haven't tried to do the processing in python (my python-fu is weak) but if that's the intended way to achieve this sort of thing i can give it a try

**Comment by wolverdude** [comment]
I would encourage you to go ahead and dive into the Python, even if it means getting lost along the way. Based on my understanding of what you're saying, you're trying to diff two schemas. This is a _lot_ easier to do with a little bit of Python code. Python dicts are order agnostic, and the GenSON `Schema` class has overridden the `==` operator. This means that you should be able to compare two schemas just by using `==`.

I've written a little code to get you started:

```python
from genson import Schema
from genson.genson import add_json_from_file

JSON_FILE_1 = '/my/path/to/file1.json'
JSON_FILE_2 = '/my/path/to/file2.json'

schema1 = Schema()
schema2 = Schema()
with open(JSON_FILE_1, 'r') as fp1, open(JSON_FILE_2, 'r') as fp2:
    add_json_from_file(schema1, fp1, '')
    add_json_from_file(schema2, fp2, '')

print('same' if schema1 == schema2 else 'different')
```

This will only tell you whether or not the schemas are the same. If you want to see specifically what's different, you'll need to use a diffing library like [deepdiff](https://github.com/seperman/deepdiff):

```python
from deepdiff import DeepDiff

DeepDiff(schema1, schema2)
```

It doesn't seem to me like this feature really belongs in the package, but I would be open to community input. Whatever the case, grappling with the code under the hood can really get you a long ways with these kinds of problems.

Hope that helps!
