### ISSUE TITLE
Where are the installation intstructions?

### ISSUE THREAD

**Issue by tychop** [wolverdude/GenSON#19]
How do we install the cli tool?

**Comment by wolverdude** [comment]
Installing the Python package will automatically install the executable.

```bash
$ pip install genson
$ which genson
```

If you're unable to access it, it might be because your `$PATH` isn't set correctly.

**Comment by wolverdude** [comment]
Hmm... on second though, you have a point. It doesn't say how to install it anywhere in the docs. I'll fix this.

**Comment by tychop** [comment]
Thnx!! 👍🏻
