### ISSUE TITLE
It does not handle patternProperties from an existing schema

### ISSUE THREAD

**Issue by lcahlander** [wolverdude/GenSON#20]
If a sample JSON contains { "123456789": { "foo": "bar" } } and the schema contains

"patternProperties": {
    "^\\d{9}$": {
        "type": "object",
        "properties": {
            "foo": { "type": "string" },
            "additionalProperties": false
        }
    }
}

It should not create the following:

"properties": {
    "123456789": {
        "type": "object",
        "properties": {
            "foo": { "type": "string" },
            "additionalProperties": false
        }
    }
},
"patternProperties": {
    "^\\d{9}$": {
        "type": "object",
        "properties": {
            "foo": { "type": "string" },
            "additionalProperties": false
        }
    }
}

If there is a patternProperties in the object, then when a new property is detected, then you should test against the patterns.  If a pattern is matched, then it is not a new property.

**Comment by wolverdude** [comment]
Thanks for the suggestion. I'll give some thought as to how that might be achieved.

**Comment by wolverdude** [comment]
I'm working on this. See my comment in PR #12 .

**Comment by wolverdude** [comment]
`"patternProperties"` is now live in version 1
