### ISSUE TITLE
Suspected bug in object.py merging existing schemas

### ISSUE THREAD

**Issue by pdiorio** [wolverdude/GenSON#22]
I believe I may have run into a bug when merge N existing json schema files. With the current codebase, running with python3.5:
`genson -s schema1.txt -s schema2.txt ... 
`
results in: 
`TypeError: unsupported operand type(s) for &=: 'NoneType' and 'set'
`
I believe the issue is on line 24 of GenSON/genson/schema/generators/object.py -- it should initialize to an empty `set()` instead of `None`.

**Comment by wolverdude** [comment]
That sounds like a bug. I'll look into it. In the meantime, can you post or link to the data you were using so I can be sure?

**Comment by wolverdude** [comment]
Fixed the bug. Thanks for reporting it! [Version 1.0.1](https://pypi.python.org/pypi/genson/1.0.1) is live on PyPI now.
