### ISSUE TITLE
final "required" should not be present

### ISSUE THREAD

**Issue by xgodon** [wolverdude/GenSON#28]
the draft-07 does not accept the final "required" in 
`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "hi": {
      "type": [
        "integer",
        "string"
      ]
    }
  },
  "required": [
    "hi"
  ]
}`

validators :
https://www.jsonschemavalidator.net/
https://jsonschemalint.com/#/version/draft-07/markup/json

i asked the json-schema team to confirm

**Comment by wolverdude** [comment]
I don't see what the issue is. That schema validates under Drafts 4, 6, and 7 (provided the value of `"$schema"` is changed accordingly).

**Comment by xgodon** [comment]
i couldn't validate this schemas on 3 validators under draft 7.
so that means that either 
- the validator is not correctly implemented
- the generator is not correctly implemented

**Comment by xgodon** [comment]
or 3rd possibility i don't understand something

**Comment by wolverdude** [comment]
I think you may be using the validators incorrectly. The test suite for GenSON includes validation for every schema generated, so if it were generating invalid schemas, the tests would fail.

Here's a screenshot of me using https://jsonschemalint.com/#/version/draft-07/markup/json to validate the same schema you posted:

![validation screen shot](https://user-images.githubusercontent.com/4276302/53989246-66028480-40da-11e9-816d-72e4413bd066.png)

Hopefully that helps!

**Comment by xgodon** [comment]
yeah i get that but with the first one and my python lib (https://github.com/Julian/jsonschema), it doesn't validate.
is their implementation not ok?

**Comment by wolverdude** [comment]
That is precisely the same library we use to validate schemas in testing. You can see how we use it [here](https://github.com/wolverdude/GenSON/blob/9bd10f92324f7c8bd6de11c5b97096c6111019f3/test/base.py#L29). Just replace `Draft4Validator` with `Draft6Validator` or `Draft7Validator` depending on what kind of schema you want to validate.

**Comment by xgodon** [comment]
Yeah but i can't validate the schemas generated with your lib with Draft7Validator is this the wanted behavior?

```
from genson import SchemaBuilder
import jsonschema
import json
from jsonschema import Draft7Validator



builder = SchemaBuilder()
builder.add_schema({ "$schema": "http://json-schema.org/draft-07/schema#", "type": "object", "properties": { "hi": { "type": [ "integer", "string" ] } }, "required": [ "hi" ] })
Draft7Validator.check_schema(builder.to_json())

```

> 
> jsonschema.exceptions.SchemaError: '{"$schema": "http://json-schema.org/draft-07/schema#", "type": "object", "properties": {"hi": {"type": ["integer", "string"]}}, "required": ["hi"]}' is not of type 'object', 'boolean'
> 
> Failed validating 'type' in metaschema:

**Comment by xgodon** [comment]
thanks

**Comment by wolverdude** [comment]
I'm assuming you figured it out. Use `builder.to_schema()`, not `builder.to_json()` which produces a JSON string, and a string is not a valid schema.

**Comment by xgodon** [comment]
You found me out :D
