### ISSUE TITLE
how to pass "required" option? 

### ISSUE THREAD

**Issue by masepehr** [wolverdude/GenSON#44]
i am building my schema dynamically like below :
` b1.add_schema({"type": "object", "properties": {"{0}".format(name): {"type": "{0}".format(atttypes[i])}}})`

i need to pass  required option to this schema.

**Comment by wolverdude** [comment]
You need to add a `required` key to the object schema and pass an array of the required keys. See [the JSON-Schema docs for Required Properties](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties).
