### ISSUE TITLE
Support apostrophe as alternate to quote

### ISSUE THREAD

**Issue by phaedron** [wolverdude/GenSON#48]
I exported a JSON file in which key property was in single quote (apostrophe). Genson objected to the use of apostrophe.

**Comment by wolverdude** [comment]
Single quote keys are invalid JSON. GenSON is just using Python's native JSON parser, and there isn't a simple and secure way to parse invalid JSON.

You'll need to pre-process the file to turn those single quotes into doubles before it can be fed into GenSON.
