### ISSUE TITLE
Comparing schema after to_json, not matching

### ISSUE THREAD

**Issue by Marco-Santoni** [wolverdude/GenSON#49]
Consider the following example:

```python
jstring1 = """{ "bar": 10, "foo": 20 }"""
builder1 = SchemaBuilder()
builder1.add_object(json.loads(jstring1))

schema = builder1.to_json()
builder2 = SchemaBuilder()
builder2.add_schema(json.loads(schema))

builder1 == builder2
False # I would expect to be True
```

Is this behaviour expected?

I dug into the object and found what was not matching:

```python
builder2.schema_uri = None
builder2._root_node._active_strategies[0]._include_empty_required = False

builder1 == builder2
True # OK
```

I would like to

- extract the schema out of a JSON A
- store the schema (using `to_json`?)
- check if the schema of a new JSON B matches the schema of A

What is the correct way of doing it in `genson`?

**Comment by wolverdude** [comment]
Turns out this bug isn't new like I thought. `v1.2.0` did break equality checking in this context, which I've fixed, but this was actually an issue where the empty required option was being activated too often. I'll be deploying the fix shortly.
