### ISSUE TITLE
DEPRECATION: genson is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by kevin-paulson-mindbridge-ai** [wolverdude/GenSON#68]
Installing via `pip 23.0.1` and `Python 3.10.6` results in the following depreciation warning:
```
  DEPRECATION: genson is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for genson ... done
```

It looks like maybe the work has been done already but a new release is needed?

**Comment by wolverdude** [comment]
Thanks for flagging. I'll play around with it this weekend and get a patch submitted.

**Comment by wolverdude** [comment]
Okay, this is totally on me. I went and modernized all the packaging a couple years ago... and then didn't actually do the last step of creating a new version 🤦‍♂️.

When I install from HEAD as-is, there's no issue. Now I just need to dig through a diff and make sure everything is ready for release.

**Comment by kevin-paulson-mindbridge-ai** [comment]
I think this was completed with https://github.com/wolverdude/GenSON/releases/tag/v1.3.0
