### ISSUE TITLE
pip3 install genson does not install __main__

### ISSUE THREAD

**Issue by marcpawl** [wolverdude/GenSON#72]
% uname -a
Darwin XXX 21.6.0 Darwin Kernel Version 21.6.0: Thu Jul  6 22:18:26 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_X86_64 x86_64
% pip3 --version
pip 23.2.1 from /Users/XXX/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)

**Comment by wolverdude** [comment]
It downloads and installs fine for me using `pip 23.2.1` on `python 3.9`, though I am running on Darwin `22.6.0`, not `21.6.0`.

What specific error message are you getting?

**Comment by wolverdude** [comment]
Closing this issue. If anyone else comes across this, please reopen it and post your full error message.
