### ISSUE TITLE
Distribute wheel package

### ISSUE THREAD

**Issue by koxudaxi** [wolverdude/GenSON#73]
@wolverdude 
Thank you for developing an excellent library.

### Request 
Could you distribute the pure python wheel package in pypi? https://pypi.org/project/genson/#files
![image](https://github.com/wolverdude/GenSON/assets/630670/6fe884ce-b49f-42c1-82f8-925fe1d25f54)

We can generate wheel package by following the command. (I don't know how you build the package. Because I can't find the command in the CI config in this repo)
https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives

### Background 
I use the `GenSON` on [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator).
The code generator can generate pydantic, TypedDict, dataclasses, and other models from Json Data using the GenSON.

I'm planning the code generator run on [pyodide](https://pyodide.org/en/stable/)
pyodide is WASM and supports only pure python wheel package to install a third-party library.
https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
So, we need the pure python package.

Thank you very much.

**Comment by simontaurus** [comment]
@wolverdude  I have the same usecase - let us know if you need support

**Comment by simontaurus** [comment]
@koxudaxi, @wolverdude  : To get started, I've create temporary forks
https://pypi.org/project/genson-wheel/
https://pypi.org/project/datamodel-code-generator-genson-wheel/releases/
I made you co-owners, so you can delete them at any time

datamodel-code-generator(-genson-wheel) now works in pyodide:
https://simontaurus.pyscriptapps.com/pydantic-codegen/

**Comment by wolverdude** [comment]
GenSON 1.3.0 is released and has a wheel: https://pypi.org/project/genson/1.3.0/#files

**Comment by simontaurus** [comment]
Great, many thanks!

**Comment by koxudaxi** [comment]
Thank you very much!!
