### ISSUE TITLE
Fixed list bugs

### ISSUE THREAD

**Issue by davek2** [wolverdude/GenSON#8]
I've created bug fixes in generator.py for two problems with list processing:
1) Genson produces incorrect items type for merged arrays - should be a dict, not a list.
For example, the schema for `["spam", "spam", "spam", "egg", "spam"]` with `merge_arrays=True` is:
`{"type": "array", "items": {"type": "string"}}`, not `{"type": "array", "items": [{"type": "string"}]}`.  The latter is a tuple (non_merged) schema where the first item is a string and subsequent items can be anything.
2) Nested arrays are always merged regardless of the `merge_arrays` setting.  Added a context variable to Schema() to recursively pass down the setting instead of always using the default True.

I tried to push a new branch with the fixes for you to review but don't have permission.  Let me know if you want to take a look.

**Comment by wolverdude** [comment]
Thanks for catching and squishing those bugs! I'll try to sneak in some time to review this week, otherwise I'll get to it this weekend.

**Comment by davek2** [comment]
PR#11 contains the same bug fixes but is based on the latest master. The test suite builds on Sokol's structure, and adds validation of data against the generated schema.  This PR supersedes PR #9 which can be deleted - I'd delete the old branch from my repo but don't know if that would cause problems.

**Comment by wolverdude** [comment]
Got it. I'll have a look at those real quick.

**Comment by wolverdude** [comment]
Your PR has been merged, and I just released [Genson 0.2.0](https://pypi.python.org/pypi/genson/0.2.0), so this should be fixed. Thanks for your help! Let me know if you run into any more issues.
